### ISSUE TITLE
Suggest an extension: Web Analyzer

### ISSUE THREAD

**Issue by NikolaBogdanovic** [madskristensen/WebExtensionPack#10]
## Suggest an extension:

Web Analyzer
https://visualstudiogallery.msdn.microsoft.com/6edc26d4-47d8-4987-82ee-7c820d79be1d

It was already in Web Essentials, and was pretty much, well, essential.

**Comment by madskristensen** [comment]
The Web Analyzer features have been moved into the VS web tooling and is no longer needed. Just get the latest ASP.NET Core Preview tooling https://www.microsoft.com/net/download#tools
