### ISSUE TITLE
Web Extension Pack asks me to restart Visual Studio every time I open it

### ISSUE THREAD

**Issue by hernandgr** [madskristensen/WebExtensionPack#12]
### Installed product versions
- Visual Studio 2015 Professional - 14.0.25431.01 Update 3
- This extension: 1.7.53

### Description
Every time I start Visual Studio, the Web Extension Pack shows installation dialog with Glyphfriend and then prompts me to restart. When Visual Studio restarts is showing the same thing and asks me to restart again on an infinite loop. I tried to manually remove/reinstall the Glyphfriend extension and reset the Web Extension Pack but Visual Studio is behaving the same each time I start it. 

![error](https://cloud.githubusercontent.com/assets/2015653/20396260/a0f0a80a-acb3-11e6-9c4d-aec0b4bfc9e1.gif)

I have checked Event Logs and can't found errors about it. Let me know if I can try anything in order to get some useful information for you.

### Steps to recreate
1. Installed Web Extension Pack
2. Restarted Visual Studio and all the extensions got installed 
3. Restarted Visual Studio and the Glyphfriend extension is showed as installed every time you start Visual Studio

### Current behavior
Web Extension Pack is asking me to restart because of Glyphfriend installation every time I start Visual Studio.

### Expected behavior
Web Extension Pack should not ask to restart each time I open it

**Comment by ghost** [comment]
I am getting the same issue. I guess I will uninstall it until there is a remedy for this issue

**Comment by tbhdbsys** [comment]
I have exactly this problem now. Any fix in sight?

**Comment by sateesh-kumar7** [comment]
@madskristensen What is the solution. You have closed the issue without disclosing the solution.
