### ISSUE TITLE
Add an extension that allows you to copy files over, as-is, from /src to /dist

### ISSUE THREAD

**Issue by brianpmccullough** [madskristensen/WebExtensionPack#15]
## Suggest an extension:
Unsure if a separate extension exists or not, but looking for a copy file extension.  Looking to basically just copy an existing "static" file (img, .js, .css, etc) from a "src" directory to a "dist" directory - without all the bundling/optimizing that takes place with a some of the other extensions.  Some more background...

Client has a legacy system that has been *developed* over the years by just copying/pasting content (files) from "DEV" to "PROD" (SharePoint).  We are now working to get this under source control and put some project structures around it.  The "vendor" files are intermixed with custom written files and organized into a very flat structure.  For example:

/Shared
  /css
  /fonts
  /img
  /js

I'd like to slowly move to a structure where "vendor" files (Bootstrap, jQuery, Angular, Knockout) are stored separate from custom written files.  Thinking that I can structure /src as we'd desire it to be, then copy things over as is today.  For example:

/Shared
  /lib
    /bootstrap
      /bootstrap.css
      /bootstrap.js
   /angular
     /angular.js
   /font-awesome
    /font-awesome.css
  /MyCustomerRoot
    /Feature1
      /Feature1.js
      /Feature2.css
    /Feature2
      /Feature2.js
      /Feature2.css
    /Core
      /Core.js
      /Core.css
   
Perhaps there is something already existing we can take advantage of, but I was not able to find anything.  Maybe we should be looking at WebPack?  I understand it at a high level, but client is a Visual Studio shop and they'd prefer to work there.  I haven't done much regarding existing Visual Studio plugins, but happy to help with some guidance!

**Comment by madskristensen** [comment]
If you write the file copying in a .cmd or PowerShell file, then you can use [Command Task Runner](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.CommandTaskRunner) to execute that on a per project or solution level. That might be a good solution
