### ISSUE TITLE
Web Extension Pack installs already installed but disabled package, again

### ISSUE THREAD

**Issue by michaelvolz** [madskristensen/WebExtensionPack#4]
### Installed product versions
- Visual Studio: 2015 Professional
### Description

Web Extension Pack installs already installed but disabled package, again. Now I have a disabled and an enabled version installed at the same time. Which produced some weird erros.

Great extension though!!!

**Comment by madskristensen** [comment]
Which extensions do you see twice?

**Comment by michaelvolz** [comment]
It was the "Add New File" extension. I disabled most of my extensions temporarily (a few days) for debugging a performance problem.

**Comment by madskristensen** [comment]
This is an issue with the Add Any File extension and the Gallery. I'm not sure what caused this but it appears that it changed its product ID which made Visual Studio think it was 2 different extensions. It's not related to the Web Extensions Pack, so I'm closing it here while I'm continuing the investigation with the Gallery team

**Comment by stevomccormack** [comment]
You have this issue as closed - what is resolution??
I no longer have 'Add Any File' extension - it does not install with Web Extension Pack 2015 when I reinstall it?

Firstly, thanks for a wonderful extension - I have used these for sometime in all versions of Visual Studio and they have quickly become essential items.

In saying that, my Web Extensions Pack has not worked in sometime now. 
I have same/similar issue to Michael.

Steps I have taken:

- Uninstall all extensions individually as well as Web Extension Pack and Web Essentials.
- Restart VS 2015
- Download and install latest Web Extension Pack 2015 
- All extensions are installed again but are disabled.
- When I enable them and restart, they are disabled again and so forth....

Desperately looking for a resolution as the tools are essential.

Cheers.

**Comment by wonea** [comment]
This works for me. DuplicateExtensionFinder finds and optionally deletes duplicate extensions.

- Close Visual Studio (otherwise you'll get permission errors)
- Run DuplicateExtensionFinder -dupes (to see what extensions are duplicated)
- Run DuplicateExtensionFinder -delete
- Start Visual Studio and re-enable the extensions you want
- Close Visual Studio and start again, and voila!

https://github.com/remcoros/DuplicateExtensionFinder
