### ISSUE TITLE
VS 2015 crashes immediately on startup

### ISSUE THREAD

**Issue by RyanCEI** [madskristensen/WebExtensionPack#6]
### Installed product versions
- Visual Studio: 2015 Enterprise
- This extension: [example 1.1.21]
### Description

VS crashes immediately on startup
### Steps to recreate

Install Web Extension Pack
Start VS
### Current behavior

Crashing
### Expected behavior

Not crashing

Log Snippet:

<entry>
    <record>472</record>
    <time>2016/03/28 18:05:25.302</time>
    <type>Error</type>
    <source>Extension Manager</source>
    <description>Extension will not be loaded because an extension with the same ID &apos;Microsoft.Windows.DevelopmentKit.Desktop&apos; is already loaded at C:\PROGRAM FILES (X86)\COMMON FILES\MICROSOFT\EXTENSIONMANAGER\EXTENSIONS\MICROSOFT\WINDOWS KITS\10\DESKTOP SDK...</description>
    <path>C:\PROGRAM FILES (X86)\COMMON FILES\MICROSOFT\EXTENSIONMANAGER\EXTENSIONS\MICROSOFT\WINDOWS KITS\8.1\DESKTOP SDK</path>
  </entry>
  <entry>
    <record>473</record>
    <time>2016/03/28 18:05:25.303</time>
    <type>Error</type>
    <source>Extension Manager</source>
    <description>Extension will not be loaded because an extension with the same ID &apos;Microsoft.Windows.DevelopmentKit.WindowsStore&apos; is already loaded at C:\PROGRAM FILES (X86)\COMMON FILES\MICROSOFT\EXTENSIONMANAGER\EXTENSIONS\MICROSOFT\WINDOWS KITS\10\WINDOWS STORE SDK...</description>
    <path>C:\PROGRAM FILES (X86)\COMMON FILES\MICROSOFT\EXTENSIONMANAGER\EXTENSIONS\MICROSOFT\WINDOWS KITS\8.1\WINDOWS STORE SDK</path>
  </entry>
[vslog.zip](https://github.com/madskristensen/WebExtensionPack/files/192243/vslog.zip)

**Comment by madskristensen** [comment]
This is a VS bug that I believe has been fixed and will be in VS2015 Update 2. In the meantime, try this https://visualstudiogallery.msdn.microsoft.com/22b94661-70c7-4a93-9ca3-8b6dd45f47cd

**Comment by AndrewDevelopment** [comment]
after two years i still find this solution still useful for solving the vs bug
