### ISSUE TITLE
Visual Studio 2015 crashes at startup

### ISSUE THREAD

**Issue by mpiesens** [madskristensen/WebExtensionPack#7]
Installed product versions:
- Visual Studio: 2015 Professional
- This extension: 1.2.36 

Description:
After installing this extension Visual Studio 2015 crashes at startup.
Before it was working fine.
I tried restarting Visual Studio, as well as my PC. No luck there.....

I gives me 2 errors in the Event Viewer:
[EventErrors.txt](https://github.com/madskristensen/WebExtensionPack/files/193146/EventErrors.txt)

**Comment by madskristensen** [comment]
Thanks for reporting this issue and sharing the event log. This is now fixed and you can test it in the CI build found at http://vsixgallery.com/extension/92e3e73b-510f-45bb-8aee-c637e83778b3/
