### ISSUE TITLE
The list with updated extensions missing in restart message prompt.

### ISSUE THREAD

**Issue by totpero** [madskristensen/WebExtensionPack#8]
### Installed product versions
- Visual Studio: [example 2015 Enterprise]
- This extension: [example 1.3.39]
### Description

In this check-in https://github.com/madskristensen/WebExtensionPack/commit/f582c3a16eea724690348ff95bc6902ef7991d1c you add list of installed extensions to restart prompt but in my restart message box i don't get this list. Look to attached print screen.
### Current behavior

he list with updated extensions missing.
### Expected behavior

In message box the list with updated extensions 

![ps](https://cloud.githubusercontent.com/assets/1710257/14519250/4cb97f6a-0226-11e6-994d-4a2e91d4d331.png)

**Comment by csrakowski** [comment]
Same for me, and I know for a fact it just installed the Web Accessibility Checker as the progress box before it told me so.
I checked the VS ActivityLog.xml, but there were no errors in there.

I am using Visual Studio 2015 Enterprise, with update 2 installed.

**Comment by madskristensen** [comment]
Thanks for the bug report. I can't repro this, but I think I may have fixed it.

Can I get you to verify the fix by following these steps, please?
1. Uninstall Web Accessibility Checker
2. Close Visual Studio
3. Install latest [CI build of Web Extension Pack](http://vsixgallery.com/extension/92e3e73b-510f-45bb-8aee-c637e83778b3/)
4. Open Visual Studio

**Comment by totpero** [comment]
The problem persist. I followed the steps but the same message prompt.

**Comment by csrakowski** [comment]
For me the CI build did actually fix it. (On 2 out of 2 tests)

**Comment by totpero** [comment]
Sorry, i test with old Web Extension version. Now is OK.
