### ISSUE TITLE
Improve the Installation Experience

### ISSUE THREAD

**Issue by Nirmal4G** [madskristensen/WebExtensionPack#9]
### Installed product versions
- Visual Studio: 2015 Enterprise
- This extension: 1.4
### Description

When installing as Admin user (say in the VS installation dir and not in the user profile dir), let the installer install the individual extensions globally not user specific
### Steps to recreate
1. VSIXInstaller.exe /a WebExtensionPack.vsix
2. Open Visual Studio
3. Installation starts
4. see the extensions manager to see if they are installed globally.
### Suggestions

When Installing show a check box to select the extensions based on dev environment like node, asp, etc...
Also when Uninstalling remove all/selected extensions that came with the Pack.

One more thing, merge it with Web Essentials
i.e. Install the web essentials features (common for all) and offer the other extensions as optional packs as when working with particular dev environment.

**Comment by ghost** [comment]
Install experience here is that after error-free install of the Web Extension Pack and error-free loading of VS 2017, nothing else appears to happen. The Web Extension Pack extension is the only one from Mads that's listed. Isn't it supposed to automatically kick off the install of the rest of his web extensions?

Suspect it's either my misunderstanding of how roaming extensions feature is supposed to work or there's some problem in how it's actually supposed to work. Mad's extensions are showing in the roaming list but the Download button is disabled. The net effect is my VS 2017 install does not have any of the web pack extensions active.
